name       : perl-regexp-common
version    : 2017060201
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/A/AB/ABIGAIL/Regexp-Common-2017060201.tar.gz : ee07853aee06f310e040b6bf1a0199a18d81896d3219b9b35c9630d0eb69089b
license    : Artistic-2.0
component  : programming.perl
summary    : Provide commonly requested regular expressions
description: |
    Provide commonly requested regular expressions
builddeps  :
    - perl-test-regexp
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
