name       : perl-regexp-common
version    : 2016060801
release    : 3
source     :
    - http://search.cpan.org/CPAN/authors/id/A/AB/ABIGAIL/Regexp-Common-2016060801.tar.gz : fc2fc178facf0292974d6511bad677dd038fe60d7ac118e3b83a1ca9e98a8403
license    : Artistic-2.0
component  : programming.perl
summary    : Provide commonly requested regular expressions
description: |
    Provide commonly requested regular expressions
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
